// Mocks generated by Mockito 5.4.2 from annotations
// in ditonton_flutter/test/presentation/pages/shows/top_rated_shows_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i7;

import 'package:ditonton_flutter/common/state_enum.dart' as _i4;
import 'package:ditonton_flutter/domain/entities/shows/show.dart' as _i5;
import 'package:ditonton_flutter/domain/usecases/shows/get_top_rated_shows.dart'
    as _i2;
import 'package:ditonton_flutter/presentation/provider/shows/top_rated_shows_notifier.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetTopRatedShows_0 extends _i1.SmartFake
    implements _i2.GetTopRatedShows {
  _FakeGetTopRatedShows_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TopRatedShowsNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockTopRatedShowsNotifier extends _i1.Mock
    implements _i3.TopRatedShowsNotifier {
  MockTopRatedShowsNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetTopRatedShows get getTopRatedShows => (super.noSuchMethod(
        Invocation.getter(#getTopRatedShows),
        returnValue: _FakeGetTopRatedShows_0(
          this,
          Invocation.getter(#getTopRatedShows),
        ),
      ) as _i2.GetTopRatedShows);
  @override
  _i4.RequestState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _i4.RequestState.empty,
      ) as _i4.RequestState);
  @override
  List<_i5.Show> get shows => (super.noSuchMethod(
        Invocation.getter(#shows),
        returnValue: <_i5.Show>[],
      ) as List<_i5.Show>);
  @override
  String get message => (super.noSuchMethod(
        Invocation.getter(#message),
        returnValue: '',
      ) as String);
  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);
  @override
  _i6.Future<void> fetchTopRatedShows() => (super.noSuchMethod(
        Invocation.method(
          #fetchTopRatedShows,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
