// Mocks generated by Mockito 5.4.2 from annotations
// in ditonton_flutter/test/presentation/provider/shows/show_detail_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:ditonton_flutter/common/failure.dart' as _i6;
import 'package:ditonton_flutter/domain/entities/shows/show.dart' as _i9;
import 'package:ditonton_flutter/domain/entities/shows/show_detail.dart' as _i7;
import 'package:ditonton_flutter/domain/repositories/show_repository.dart'
    as _i2;
import 'package:ditonton_flutter/domain/usecases/shows/get_show_detail.dart'
    as _i4;
import 'package:ditonton_flutter/domain/usecases/shows/get_show_recommendations.dart'
    as _i8;
import 'package:ditonton_flutter/domain/usecases/shows/get_watchlist_show_status.dart'
    as _i10;
import 'package:ditonton_flutter/domain/usecases/shows/remove_watchlist_show.dart'
    as _i12;
import 'package:ditonton_flutter/domain/usecases/shows/save_watchlist_show.dart'
    as _i11;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeShowRepository_0 extends _i1.SmartFake
    implements _i2.ShowRepository {
  _FakeShowRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetShowDetail].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetShowDetail extends _i1.Mock implements _i4.GetShowDetail {
  MockGetShowDetail() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ShowRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeShowRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.ShowRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.ShowDetail>> execute(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [id],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, _i7.ShowDetail>>.value(
            _FakeEither_1<_i6.Failure, _i7.ShowDetail>(
          this,
          Invocation.method(
            #execute,
            [id],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.ShowDetail>>);
}

/// A class which mocks [GetShowRecommendations].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetShowRecommendations extends _i1.Mock
    implements _i8.GetShowRecommendations {
  MockGetShowRecommendations() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ShowRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeShowRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.ShowRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i9.Show>>> execute(dynamic id) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [id],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, List<_i9.Show>>>.value(
            _FakeEither_1<_i6.Failure, List<_i9.Show>>(
          this,
          Invocation.method(
            #execute,
            [id],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i9.Show>>>);
}

/// A class which mocks [GetWatchListShowStatus].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWatchListShowStatus extends _i1.Mock
    implements _i10.GetWatchListShowStatus {
  MockGetWatchListShowStatus() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ShowRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeShowRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.ShowRepository);
  @override
  _i5.Future<bool> execute(int? id) => (super.noSuchMethod(
        Invocation.method(
          #execute,
          [id],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
}

/// A class which mocks [SaveWatchlistShow].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveWatchlistShow extends _i1.Mock implements _i11.SaveWatchlistShow {
  MockSaveWatchlistShow() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ShowRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeShowRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.ShowRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, String>> execute(_i7.ShowDetail? show) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [show],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, String>>.value(
            _FakeEither_1<_i6.Failure, String>(
          this,
          Invocation.method(
            #execute,
            [show],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, String>>);
}

/// A class which mocks [RemoveWatchlistShow].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveWatchlistShow extends _i1.Mock
    implements _i12.RemoveWatchlistShow {
  MockRemoveWatchlistShow() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ShowRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeShowRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.ShowRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, String>> execute(_i7.ShowDetail? show) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [show],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, String>>.value(
            _FakeEither_1<_i6.Failure, String>(
          this,
          Invocation.method(
            #execute,
            [show],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, String>>);
}
